// GENERATED by scripts/gen-theme.mjs - do not edit by hand.
// Mirrors the ACCENTS list there, so the picker cannot drift from the CSS.

export type Accent = (typeof ACCENTS)[number]["id"];

export const ACCENTS = [
  { id: "purple", label: "Purple", seed: "#6750a4" },
  { id: "teal", label: "Teal", seed: "#0f766e" },
  { id: "violet", label: "Violet", seed: "#7c4dff" },
  { id: "amber", label: "Amber", seed: "#b45309" },
  { id: "olive", label: "Olive", seed: "#3f6212" },
  { id: "blue", label: "Blue", seed: "#0284c7" },
  { id: "brown", label: "Brown", seed: "#795548" },
] as const;

/** The one on bare `:root`, i.e. what renders with no data-accent set. */
export const DEFAULT_ACCENT: Accent = "purple";
